# Default initial positions for mario ros2_control fake system
arm1_initial_positions:
    joint1: 0
    joint2: 0
    joint3: 0
    joint4: 0
    joint5: 0
    joint6: 0

arm2_initial_positions:
    joint1: 0
    joint2: 0
    joint3: 0
    joint4: 0
    joint5: 0
    joint6: 0

arm3_initial_positions:
    joint1: 0
    joint2: 0
    joint3: 0
    joint4: 0
    joint5: 0
    joint6: 0